/**
 * strings.ts — every ShadowClock UI string (English).
 *
 * Defines: STRINGS (the app's string table, passed to startPlatform()).
 * Used by: main.ts; every ui/ and features/ module reads it through ui/context.ts t().
 * Depends on: static-web-platform (StringTable type).
 *
 * WHY one table: the static-web-app rule — one language per app, no inline UI text, and a
 * missing key throws (so the verification gate catches it). Keys are grouped by screen.
 * Placeholders use {name} and are filled by t(key, { name }).
 */

import type { StringTable } from "static-web-platform";

export const STRINGS: StringTable = {
  en: {
    // ---- App shell
    "app.tagline": "Time & place from shadows",
    "app.skip": "Skip to content",
    "app.inputs": "Inputs",
    "app.results": "Results",
    "app.footer": "Everything is computed in your browser; nothing you enter is sent anywhere. Map tiles load only if you allow them. Solar positions: NREL SPA.",
    "app.expert": "Expert",
    "app.expertTitle": "Show every option at once",
    "app.examples": "Examples",
    "app.help": "How it works",
    "app.menu": "Menu",
    "app.mode": "Mode",
    "app.findTime": "Find the time",
    "app.findTimeTitle": "Known place → when was it taken?",
    "app.findPlace": "Find the place",
    "app.findPlaceTitle": "Known times → where was it taken?",
    "app.settings": "Settings",
    "msg.forShadow": "{shot}: {text}",

    // ---- Expert-view panel titles
    "panel.where": "Where was it taken?",
    "panel.shadows": "Shadows",
    "panel.known": "What do you already know?",
    "panel.shadowsTimes": "Shadows and their times",
    "panel.area": "Search area",

    // ---- Empty states, progress, announcements, toasts
    "empty.time1": "Enter the place (paste coordinates or a map link).",
    "empty.time2": "Measure a vertical object and its shadow — add more objects or photos to sharpen the result.",
    "empty.time3": "Say what you already know: years, months, time of day.",
    "empty.place1": "Measure a shadow in each photo and give the time each was taken.",
    "empty.place2": "Two or more photos at different times cross to a small area.",
    "empty.examples": "Or start from an example:",
    "empty.needed": "Still needed",
    "empty.cannot": "Cannot compute yet",
    "progress.computing": "Computing…",
    "progress.scanning": "Scanning {year}",
    "progress.refining": "Refining {year}",
    "progress.heatmap": "Drawing the year map",
    "progress.map": "Refining the map",
    "progress.regions": "Grouping areas",
    "announce.period": "Answer updated: {n} possible period.",
    "announce.periods": "Answer updated: {n} possible periods.",
    "announce.noTime": "Answer updated: no compatible time.",
    "announce.area": "Answer updated: {n} candidate area.",
    "announce.areas": "Answer updated: {n} candidate areas.",
    "announce.noPlace": "Answer updated: no compatible place.",
    "toast.example": "Example loaded — true answer: {answer}",

    // ---- Share & export
    "share.menu": "Share and export",
    "share.tool": "Copy link to the tool",
    "share.toolSub": "A clean link with no data: safe to post anywhere.",
    "share.toolDone": "Link to the tool copied — it contains no case data.",
    "share.calc": "Share this calculation…",
    "share.calcSub": "Contains all your inputs (place, times, measurements). You will see exactly what before anything is copied.",
    "share.calcDone": "Calculation link copied. It contains all your inputs — share it with care.",
    "share.copyPrompt": "Copy this link:",
    "share.item.mode": "Mode",
    "share.item.place": "Place",
    "share.item.shadow": "{label}",
    "share.item.constraints": "Years, months, time of day, time zone",
    "share.item.claim": "Claimed time",
    "share.item.area": "Search area",
    "share.item.none": "(empty)",
    "export.json": "Download report (JSON)",
    "export.jsonSub": "Inputs, method, results and a SHA-256 of the inputs.",
    "export.print": "Print / save as PDF",
    "export.newCase": "Start a new case",
    "export.newCaseConfirm": "Start a new case? The current inputs will be cleared.",

    // ---- Help dialog
    "help.title": "How ShadowClock works",
    "help.intro": "A vertical object of height H casts a shadow of length L on level ground. The Sun's elevation is then atan(H / L), and the Sun stands opposite the shadow's direction. ShadowClock searches for every instant (or place) where the Sun was at that position, using the NREL Solar Position Algorithm.",
    "help.time1": "Enter the place, and how precisely you know it.",
    "help.time2": "Measure one or more shadows. Add another object in the same photo, or another photo of the same place with its time gap (EXIF differences are usually exact even when the camera clock is wrong).",
    "help.time3": "Narrow the search with what you know: years, months, time of day.",
    "help.place": "Give each shadow the time it was taken. One shadow places you on a ring around the point where the Sun was overhead; each extra shadow at another time adds a ring, and the rings cross at the answer.",
    "help.readTitle": "Reading the results honestly",
    "help.twiceLabel": "Twice a year:",
    "help.twice": "the Sun follows almost the same path on two dates placed symmetrically around a solstice, so a shadow usually matches two periods per year. Near a solstice they merge into one wide period.",
    "help.noYearLabel": "No year:",
    "help.noYear": "the Sun's path repeats every year. Shadows cannot tell years apart.",
    "help.boundsLabel": "Declared tolerances:",
    "help.bounds": "every measurement is a value ± the largest error you consider possible. ShadowClock treats it as a hard bound and adds the physical margins it knows about (the blurred shadow tip, the object's lean, refraction), all listed in the error budget. A time is listed when it fits inside every bound.",
    "help.assumeTitle": "Assumptions",
    "help.assume1": "The object is vertical (within the lean you give) and the ground is flat and level where the shadow falls.",
    "help.assume2": "Lengths and directions are measured in the real scene or on a rectified image — perspective in a raw photo distorts both.",
    "help.assume3": "Directions are relative to true north; convert compass readings with the local magnetic declination.",

    // ---- Guided steps and start screen
    "landing.title": "What do you want to find out?",
    "landing.when": "When was this photo taken?",
    "landing.whenSub": "You know the place. The shadows give the date and time.",
    "landing.where": "Where was this photo taken?",
    "landing.whereSub": "You know when. The shadows give the place.",
    "landing.examples": "New here? Load an example whose true answer is known:",
    "guided.where": "Where was the photo taken?",
    "guided.measure": "Measure a vertical object and its shadow",
    "guided.more": "Anything else in the picture?",
    "guided.moreIntro": "Each extra shadow narrows the answer.",
    "guided.moreInfoTitle": "Extra shadows",
    "guided.moreInfo": "Another object in the same photo shares its instant. Another photo of the same place needs the time gap after the first photo — the difference between the two EXIF timestamps is usually exact, even when the camera clock is wrong.",
    "guided.known": "What do you already know?",
    "guided.measureTimed": "Measure a shadow and say when it was taken",
    "guided.otherPhotos": "Other photos of the same place",
    "guided.otherIntro": "Photos at other times cross at the answer.",
    "guided.otherInfoTitle": "Why more photos",
    "guided.otherInfo": "One shadow places you on a ring of possible places. Each photo taken at another time adds a ring; the rings cross where the photos were taken.",
    "guided.area": "Where could it be?",
    "guided.areaBox": "Box {box}",
    "guided.nothingElse": "Nothing else",
    "guided.edit": "Edit",
    "guided.open": "Open",
    "guided.optional": "optional",
    "guided.continue": "Continue",
    "guided.showAnswer": "Show the answer",

    // ---- Info buttons, shadow names
    "info.more": "More about {title}",
    "info.title": "More information",
    "info.ok": "Got it",
    "shot.default": "Shadow {n}",
    "shot.object": "Object {n}",
    "shot.photo": "Photo {n}",
    "shot.copyOf": "{label} (copy)",

    // ---- Core: errors
    "core.err.field": "{field}: {reason}",
    "core.field.heightShadow": "Height/shadow",
    "core.field.ratio": "Ratio",
    "core.field.elevation": "Elevation",
    "core.field.azimuth": "Direction",
    "core.err.missing": "a value is missing",
    "core.err.negativeSigma": "the uncertainty must be ≥ 0",
    "core.err.minAboveMax": "the minimum is larger than the maximum",
    "core.err.notPositive": "values must be > 0",
    "core.err.mixedKinds": "Height and shadow must use the same error type",
    "core.err.tilt": "The lean must be between 0° and 45°",
    "core.err.belowHorizon": "The implied Sun elevation is not above the horizon",
    "core.err.declination": "The declination is missing",
    "core.err.noShadow": "Add at least one shadow",
    "core.err.location": "The location is invalid",
    "core.err.radius": "The location radius must be ≥ 0",
    "core.err.yearsInteger": "Years must be whole numbers",
    "core.err.yearsOrder": "The first year is after the last year",
    "core.err.yearsRange": "Years must be within {min}–{max}",
    "core.err.yearsSpan": "At most {max} years per search",
    "core.err.months": "Select at least one month",
    "core.err.offset": "invalid time gap",
    "core.err.timeMissing": "the date and time are missing",
    "core.err.timeTolerance": "invalid time tolerance",
    "core.err.emptyArea": "The search area is empty",
    "core.err.claimMissing": "Enter the claimed date and time",
    "core.err.worker": "The computation stopped unexpectedly: {detail}",
    "core.err.internal": "Internal error: {detail}",

    // ---- Core: warnings
    "core.warn.lowSun": "Low Sun (< 5°): refraction is large and variable; results are less reliable.",
    "core.warn.wideElevation": "Elevation uncertainty exceeds 5°: expect very wide windows.",
    "core.warn.highSun": "Sun above 80°: the shadow is short, so its direction is poorly defined.",
    "core.warn.noYear": "The Sun's path repeats every year, so shadows alone cannot give the year: every year in the range is solved separately.",
    "core.warn.noAzimuth": "No direction given: each day has a morning and an afternoon solution. Adding the shadow direction removes this ambiguity.",
    "core.warn.noTime": "No time is compatible with the measurements and constraints. Check the inputs, the location or the tolerances.",
    "core.warn.truncated": "Some solutions are cut by a constraint or by the search range; they may extend beyond what is shown.",
    "core.warn.solstice": "A solution lies near a solstice, where the Sun's declination changes slowly: the date is poorly constrained there and the two yearly solutions can merge.",
    "core.warn.inconsistent": "Even the best-fitting time lies outside the 95 % region: the measurements may be inconsistent (wrong north reference, tilted object, sloped ground?).",
    "core.warn.coarse": "Result shown at {size}° resolution: the candidate area is too large to refine further. Narrow the search area or add shadows.",
    "core.warn.noPlace": "No place on Earth matches all shadows at the given times. Check the times (UTC!), the north reference and the tolerances.",
    "core.warn.ring": "A single shadow without direction only gives a ring of possible places. Add the shadow direction or a second shadow at another time.",

    // ---- Error budget terms
    "budget.lengths": "Height & shadow length",
    "budget.ratio": "Height/shadow ratio",
    "budget.angle": "Elevation reading",
    "budget.tipEdge": "Shadow tip edge (penumbra)",
    "budget.tipMidpoint": "Shadow tip midpoint judgement",
    "budget.tilt": "Object lean",
    "budget.refraction": "Refraction model",
    "budget.azimuth": "Direction reading",

    // ---- Field names and form validation
    "field.height": "Object height",
    "field.shadow": "Shadow length",
    "field.ratio": "Height ÷ shadow",
    "field.elevation": "Sun elevation",
    "field.direction": "Direction",
    "field.declination": "Declination",
    "field.lean": "Max lean",
    "field.pressure": "Air pressure",
    "field.temperature": "Temperature",
    "field.deltaT": "ΔT",
    "field.radius": "Radius",
    "field.siteHeight": "Height above sea level",
    "field.yearFrom": "From year",
    "field.yearTo": "To year",
    "val.number": "{what}: enter a number",
    "val.min": "{what} must be ≥ {min}",
    "val.tolerance": "{what}: declare the tolerance (0 if exact)",
    "val.toleranceTooBig": "{what}: the tolerance must be smaller than the value",
    "val.locationBad": "Location not recognised",
    "val.locationNeeded": "Enter the location (or pick it on a map)",
    "val.offsetBad": "Offset not recognised (e.g. +02:00)",
    "val.zoneBad": "Unknown time zone (e.g. Europe/Paris)",
    "val.hhmm": "Use HH:MM",
    "val.dateBad": "Date not recognised (e.g. 2024-06-01 or 2024-06-01 14:00)",
    "val.gap": "Time after the first photo, e.g. +01:23:04 or 85 min",
    "val.gapTolerance": "Declare the tolerance of the time gap, e.g. 2 s",
    "val.todBoth": "Give both ends of the time-of-day window",
    "val.dateTimeBad": "Date/time not recognised",
    "val.whenTaken": "Enter when this photo was taken",
    "val.timeTolerance": "Declare the time tolerance, e.g. 30 s or 2 min",
    "val.bbox": "Use: south, west, north, east (e.g. 40, -5, 52, 10)",
    "val.claimNeeded": "Enter the claimed time",

    // ---- Months and zones
    "month.0": "Jan",
    "month.1": "Feb",
    "month.2": "Mar",
    "month.3": "Apr",
    "month.4": "May",
    "month.5": "Jun",
    "month.6": "Jul",
    "month.7": "Aug",
    "month.8": "Sep",
    "month.9": "Oct",
    "month.10": "Nov",
    "month.11": "Dec",
    "zone.utc": "UTC",
    "zone.solar": "Local mean solar time",

    // ---- Examples
    "ex.paris": "Two objects in one photo",
    "ex.parisDesc": "Paris, 15 Apr 2025 09:20 UTC. A post and a lamp standard in the same picture; the EXIF clock says 11:20 with no offset.",
    "ex.bollard": "Bollard",
    "ex.lamp": "Lamp standard",
    "ex.sydney": "Two photos, known time gap",
    "ex.sydneyDesc": "Sydney, 10 Dec 2024 01:30 UTC, and a second photo 2 h 15 min later (from the EXIF difference). Near the solstice.",
    "ex.post1": "Photo 1 – fence post",
    "ex.post2": "Photo 2 – same post",
    "ex.tromso": "No compass, high latitude",
    "ex.tromsoDesc": "Tromsø, 20 Aug 2024 10:00 UTC. Only the ratio of a building's height to its shadow is known, with a tolerance.",
    "ex.building": "Building",
    "ex.athens": "Find the place: three photos",
    "ex.athensDesc": "Athens, 2 Jun 2023 at 06:30, 09:45 and 14:10 UTC. Elevation only — the three rings cross at one place.",

    // ---- Place and search area
    "site.notSet": "Not set",
    "site.within": "within {r} {unit}",
    "site.notRecognised": "Not recognised yet",
    "site.coords": "Coordinates",
    "site.coordsPlaceholder": "48.8584, 2.2945 or a map link",
    "site.coordsInfo": "Paste coordinates in any usual form: decimal (48.8584, 2.2945), degrees-minutes-seconds (48°51′30″N 2°17′40″E), or a Google Maps / OpenStreetMap link. You can also pick the place on a map.",
    "site.knownWithin": "Known to within",
    "site.precisionTitle": "Place precision",
    "site.precisionInfo": "The photo was taken somewhere within this distance of the coordinates. It is a hard bound: ShadowClock checks every position inside it.",
    "site.precisionPresets": "Exact spot = 10 m · Street = 100 m · Town = 5 km · Region = 50 km.",
    "site.preset.spot": "Exact spot",
    "site.preset.street": "Street",
    "site.preset.town": "Town",
    "site.preset.region": "Region",
    "site.other": "Other…",
    "site.unit": "unit",
    "area.search": "Search",
    "area.info": "If you already know the country or region, restrict the search to a box: it is faster and removes far-away look-alikes.",
    "area.world": "Whole Earth",
    "area.box": "Bounding box",
    "area.boxLabel": "South, west, north, east (degrees)",

    // ---- Settings and constraints
    "adv.refraction": "Atmospheric refraction",
    "adv.refractionTitle": "Refraction",
    "adv.refractionInfo": "The air bends sunlight, raising the Sun slightly — up to half a degree near the horizon. Keep it on for real photos. Pressure and temperature fine-tune it; the defaults suit almost every photo.",
    "adv.deltaT": "ΔT override (TT − UT)",
    "adv.deltaTPlaceholder": "model",
    "adv.deltaTInfo": "Difference between atomic and Earth-rotation time. Leave empty to use the Espenak–Meeus model; one second changes the Sun by only ~0.004°.",
    "cons.dateBoundsShort": "date bounds",
    "cons.thisYear": "This year",
    "cons.last5": "Last 5 years",
    "cons.last20": "Last 20 years",
    "cons.showIn": "Show times in",
    "cons.zoneIana": "Time zone",
    "cons.zoneOffset": "UTC offset",
    "cons.months": "Months",
    "cons.allMonths": "All",
    "cons.maySep": "May–Sep",
    "cons.octApr": "Oct–Apr",
    "cons.tod": "Time of day",
    "cons.todInfo": "In the zone chosen above. A window like 22:00 → 04:00 wraps past midnight.",
    "cons.from": "From",
    "cons.to": "To",
    "cons.dateBounds": "Date bounds",
    "cons.dateBoundsInfo": "E.g. not after the upload date, not before a building visible in the photo was finished.",
    "cons.notBefore": "Not before",
    "cons.notAfter": "Not after",
    "cons.whichYears": "Which years should be checked?",
    "cons.years": "Years",
    "cons.yearsInfo": "The Sun follows the same path every year, so shadows cannot tell years apart. Every year in the range is checked separately.",
    "cons.more": "More: season, time of day, dates",

    // ---- Shadow cards
    "unit.d": "d",
    "unit.h": "h",
    "unit.min": "min",
    "unit.s": "s",
    "compass.n": "N",
    "compass.e": "E",
    "compass.s": "S",
    "compass.w": "W",
    "shot.waiting": "Waiting for measurements…",
    "shot.previewElevation": "Sun elevation {value}",
    "shot.previewAzimuth": "azimuth {value}",
    "shot.diagram": "Height H of a vertical object, its shadow length L on flat ground, and the Sun elevation angle at the shadow tip",
    "shot.compass": "Compass",
    "shot.compassValue": "Shadow points to {shadow}°, the Sun is at {sun}°",
    "shot.info.h": "Height of a vertical object (post, pole, person, wall edge). Any unit, as long as the shadow uses the same one: only the ratio matters.",
    "shot.info.l": "Length of its shadow on flat, level ground, from the base of the object to the tip.",
    "shot.info.r": "Height divided by shadow length, when the scene gives proportions but no absolute size.",
    "shot.info.a": "The Sun's angle above the horizon, if you already know it (e.g. from a solved scene).",
    "shot.info.tol": "The largest error you consider possible for each value. It is a hard bound: the true value is certainly within ± this amount. Use 0 only if the value is exact.",
    "shot.info.az": "Direction from the base of the object to the tip of its shadow, clockwise from true north (0° = N, 90° = E). Optional: leave empty if unknown. Without it, each day has a morning and an afternoon solution.",
    "shot.sumRatio": "ratio {v}",
    "shot.sumDir": "dir {v}°",
    "shot.max": "Maximum {n} shadows reached.",
    "shot.addObject": "Another object",
    "shot.addObjectSub": "in this same photo",
    "shot.addPhoto": "Another photo",
    "shot.addPhotoSub": "of this place, taken later or earlier",
    "shot.addPhotoPlaceSub": "taken at another time",
    "shot.introTime": "Add another object in the same photo, or another photo of the same place taken a known time later — each one tightens the result.",
    "shot.introPlace": "Give each photo its own time. Shadows taken at different times are crossed to pin down the place.",
    "shot.phDegrees": "degrees",
    "shot.phValue": "value",
    "shot.phMax": "max",
    "shot.phOptional": "optional",
    "shot.tol": "±",
    "shot.relation": "Relation to the first shadow",
    "shot.samePhoto": "Same photo",
    "shot.samePhotoTitle": "Another vertical object in the same picture: same instant",
    "shot.otherPhoto": "Another photo",
    "shot.otherPhotoTitle": "A different photo of the same place, taken a known time later or earlier",
    "shot.gap": "Taken after the first photo",
    "shot.gapInfo": "Time between the first photo and this one, e.g. +01:23:04, −5 min or 2 h 10 min. Take it from the difference between the two EXIF timestamps: it is reliable even when the camera clock itself is wrong.",
    "shot.tolerance": "± tolerance",
    "shot.takenAt": "Taken at",
    "shot.offsetFromText": "Offset read from the text",
    "shot.takenAtInfo": "Paste the EXIF DateTimeOriginal (2024:07:14 15:32:10) or an ISO 8601 date. If the text has no offset, the UTC offset field is used.",
    "shot.northRef": "North reference",
    "shot.trueNorth": "True north",
    "shot.trueNorthTitle": "Map / geographic north",
    "shot.magnetic": "Magnetic (compass)",
    "shot.magneticTitle": "Compass reading: needs the local magnetic declination",
    "shot.declination": "Declination (east +)",
    "shot.declTitle": "Magnetic declination",
    "shot.declInfo": "A compass points to magnetic north. Enter the local declination for the place and date (east positive), e.g. from the NOAA magnetic field calculator (ngdc.noaa.gov).",
    "shot.name": "Name",
    "shot.inputAs": "Input as",
    "shot.lengths": "Height + shadow",
    "shot.ratio": "Ratio",
    "shot.angle": "Angle",
    "shot.tip": "Tip measured at",
    "shot.tipTitle": "Shadow tip",
    "shot.tipInfo": "The Sun is not a point, so the end of a shadow is blurred over about half a degree. If you measured to the sharp inner edge or the faint outer edge, say so; otherwise ShadowClock adds ±0.27° to be safe.",
    "shot.tipUnknown": "Not sure (± 0.27°)",
    "shot.tipMidpoint": "Middle of soft edge",
    "shot.tipUmbra": "Sharp inner edge",
    "shot.tipOuter": "Faint outer edge",
    "shot.leanInfo": "How far the object could be from perfectly vertical. Posts, poles and walls are rarely exactly plumb; 1° is a safe default.",
    "shot.more": "More options",
    "shot.inputTitle": "Input",
    "shot.inputInfo": "Height + shadow: two lengths in the same unit. Ratio: height ÷ shadow when only proportions are known. Angle: the Sun's elevation directly, e.g. from a solved scene.",
    "shot.direction": "Shadow direction",
    "shot.knowDirection": "I know which way the shadow points",
    "shot.duplicate": "Duplicate",
    "shot.remove": "Remove",
    "shot.timeNeeded": "time needed",
    "shot.reference": "reference",
    "shot.samePhotoBadge": "same photo",
    "shot.otherPhotoBadge": "other photo",

    // ---- Claimed-time check
    "claim.title": "Does a claimed time match?",
    "claim.subtitle": "EXIF, post date, witness…",
    "claim.time": "Claimed time",
    "claim.timeInfo": "The time the photo claims: EXIF DateTimeOriginal (2024:07:14 15:32:10), a post date, a witness statement.",
    "claim.offsetPlaceholder": "unknown",
    "claim.offsetInfo": "Leave empty if the offset is unknown (EXIF often has none): every offset from UTC−12 to UTC+14 is tested, and the compatible ones are listed.",
    "claim.outside": "outside the 99.7 % region",
    "claim.insideBounds": "inside all bounds",
    "claim.insideLevel": "inside the {pct} % region",
    "claim.consistent": "Consistent with the shadows",
    "claim.inconsistent": "Not consistent with the shadows",
    "claim.levelSentence": "{time} is {level}.",
    "claim.nearest": "Nearest compatible time: {time} — {dist} away.",
    "claim.shotDetail": "{shot}: the Sun would be at {el}° elevation, {az}° azimuth (difference {residual}).",
    "claim.stripLabel": "Compatible offsets: {list}",
    "claim.none": "none",
    "claim.compatibleIf": "Compatible if the clock was on UTC{offset}",
    "claim.noOffset": "No UTC offset makes this time compatible",
    "claim.compatibleList": "Compatible: {list}",
    "claim.wrong": "The date, the clock or the measurements are wrong.",
    "claim.readingTitle": "Reading this",
    "claim.readingOk": "These are the UTC offsets that make the claimed clock time agree with the shadows. The legal time zone of the place in that season should be one of them; if it is not, the camera clock or the claim is wrong.",
    "claim.readingNone": "No UTC offset makes the claimed time agree with the shadows. The answer above lists the times that do.",
    "claim.range": "UTC{from} to {to}",

    // ---- Time results
    "res.morning": "morning",
    "res.afternoon": "afternoon",
    "res.noon": "around noon",
    "res.yearMap": "The year at a glance",
    "res.yearMapTitle": "Year map",
    "res.yearMapInfo": "Each column is a day, each row a time of day. Blue marks the possible times; numbers match the answers.",
    "res.yearMapUse": "Tap or click a spot to check it in the sky view. On a computer, drag to zoom and double-click to reset.",
    "res.legendPossible": "possible",
    "res.legendClose": "close, but outside",
    "res.legendExcluded": "excluded",
    "res.sky": "Sky check",
    "res.skyInfo": "The Sun's path across the sky on the selected day, compared with the Sun position each shadow implies (boxes = your declared bounds). A good time passes through every box.",
    "res.evidence": "Show the evidence",
    "res.evidenceTimeSub": "Year map, daily windows, sky check",
    "res.budget": "Error budget",
    "res.noTime": "No compatible time found.",
    "res.answer": "Answer",
    "res.readTitle": "How to read this",
    "res.readInfo": "Every listed time fits inside all the tolerances you declared, plus the physical margins (blurred shadow tip, lean, refraction). The periods are equally possible: nothing is ranked.",
    "res.readInfo2": "The Sun repeats the same path on two dates each year, and every year: that is why several periods appear.",
    "res.onePeriod": "One possible period:",
    "res.onePeriodYearly": "One possible period each year:",
    "res.periods": "{n} possible periods:",
    "res.periodsYearly": "{n} possible periods each year:",
    "res.showInEvidence": "Show this solution in the evidence",
    "res.cut": "cut",
    "res.cutTitle": "Cut by a constraint or the search range",
    "res.summary": "Summary",
    "res.metaShadow": "Times in {zone} · {n} shadow",
    "res.metaShadows": "Times in {zone} · {n} shadows",
    "res.notes": "Notes ({n})",
    "res.showAllDays": "Show all {n} days",
    "res.bestFitDay": "Best fit: {time} — {n} day, each day's window lasts up to {span}.",
    "res.bestFitDays": "Best fit: {time} — {n} days, each day's window lasts up to {span}.",
    "res.colDate": "Date",
    "res.colBest": "Best",
    "res.colPossible": "Possible",
    "res.colSolar": "Solar",
    "res.colSolarTitle": "Local apparent solar time",
    "res.showOnCharts": "Show on charts",
    "res.copy": "Copy",
    "res.copied": "Copied",
    "res.solutions": "Solutions",
    "res.nothing": "Nothing to list.",
    "res.nSolution": "{n} solution",
    "res.nSolutions": "{n} solutions",
    "res.skyEmpty": "Select a solution to compare the Sun's path with the measurements.",
    "res.selected": "Selected: {time}",
    "res.copyHead": "Solution {n}: {dates}, {tod} ({zone})",
    "res.copyBest": "best {time}",

    // ---- Map and place results
    "map.attribution": "&copy; <a href=\"https://www.openstreetmap.org/copyright\" target=\"_blank\" rel=\"noopener noreferrer\">OpenStreetMap</a> contributors",
    "map.privacyTitle": "Map privacy",
    "map.privacyInfo": "Map tiles come from OpenStreetMap. Loading them tells the tile server which area you are looking at, and this site's address. You will be asked first; your choice can be changed in Privacy.",
    "map.pick": "Pick on a map",
    "map.show": "Show on a map",
    "res.evidencePlaceSub": "All areas, error budget",
    "place.where": "Where it could be",
    "place.realMap": "Show on a real map",
    "place.realMapInfo": "The plot above uses no map data. A real map loads tiles from OpenStreetMap, which tells the tile server which area you are looking at. You will be asked first.",
    "place.oneArea": "One candidate area.",
    "place.areas": "{n} candidate areas.",
    "place.none": "No compatible place found.",
    "place.around": "around {pos} · {area}",
    "place.metaShadow": "{n} shadow · grid {grid}°",
    "place.metaShadows": "{n} shadows · grid {grid}°",
    "place.areasTitle": "Candidate areas",
    "place.first50": "Showing the first 50 of {n}.",
    "place.colCentre": "Centre",
    "place.colExtent": "Extent (S, W – N, E)",
    "place.colArea": "Area",
    "place.copyCoords": "Copy coordinates",
    "place.openOsm": "Open in OSM",

    // ---- Budget, heatmap, sky chart
    "budget.advice.tipEdge": "State which edge of the shadow tip you measured to remove this term.",
    "budget.advice.lengths": "Measure the height and shadow length more precisely.",
    "budget.advice.tilt": "Pick an object that is certainly vertical (a plumb line, a door frame, a lamp post).",
    "budget.advice.refraction": "The Sun is low; this term cannot be reduced much.",
    "budget.advice.azimuth": "Measure the shadow direction more precisely (true north reference, longer shadow).",
    "budget.totalSigma": "± {v}° (1σ)",
    "budget.totalBounds": "± {v}° (bounds)",
    "budget.lever": "Biggest lever: {advice}",
    "heat.excluded": "excluded by your constraints",
    "heat.possible": "possible (inside every declared bound)",
    "heat.outsideBound": "outside ({x}× the declared bound)",
    "heat.outsideLevel": "outside (misfit {x}× the 95 % limit)",
    "heat.label": "Year map: day of year horizontally, time of day vertically",
    "heat.reset": "Reset zoom",
    "place.plotLabel": "Candidate areas on a latitude/longitude grid",
    "sky.label": "Sun path on {date} with the measured Sun positions",
    "sky.elevationOnly": "{shot} (elevation only)",
    "sky.legendPath": "Sun path, {date}",

    // ---- Report
    "report.printHeader": "{app} version {version} · report generated {time} · inputs SHA-256 {sha}",
  },
};
